spring.application.name=backend
spring.datasource.url=jdbc:postgresql://localhost:5432/backend
spring.datasource.username=admin
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml

app.jwt.secret=MojeBardzoBezpieczneISecretHasloKtoreMaPonad32Znaki
app.reset-password.url=http://localhost:8080/reset-password

#spring.mail.host=
#spring.mail.port=
#spring.mail.username=
#spring.mail.password=
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true

spring.mail.host=localhost
spring.mail.port=1025